sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.3

install:
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    - source
