# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'
timezone: Europe/Madrid

# Website info
name: 'raycoarana'
description: "My coding adventures and other random stuff"

# Author's info
author: 'Rayco Araña'
# edit 'categories' in the front matter of every post to match this username
nickname: raycoarana
bio: 'Software engineer, gamer, photographer and "mother of dragons" follower.'
location: 'Madrid, Spain'
url: 'https://raycoarana.com/'
image: 'assets/images/avatar.jpg'
logo: 'assets/images/main-logo.png'

short_url: 'raycoarana.com'
google_analytics: UA-48361320-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ""

# Permalinks
permalink: /blog/:year/:month/:title/
# permalink: /author/:username
# permalink: /tag/:tag

excerpt_separator: <!--more-->

# gems and other configs
plugins: 
  - jekyll-paginate

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

exclude:
  - .git
  - .github
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - cSpell.json

# Settings for builing master branch with CI

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
username: raycoarana
repo: raycoarana.github.io
destination: _site
