name: release
on:
  push:
    branches:
      - 'source'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout master in _site
        uses: actions/checkout@v3
        with:
          ref: master
          path: _site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'
          bundler-cache: true
      - name: Build & Deploy
        run: bundle exec rake site:deploy
